branch-defaults:
  default:
    environment: null
    group_suffix: null
environment-defaults:
  workshop01-env:
    branch: null
    repository: null
  workshop01-new:
    branch: null
    repository: null
global:
  application_name: workshop01
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.8
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
