---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: myns
  labels:
    name: mypod
spec:
  containers:
  - name: dov-bear
    image: stackupiss/northwind-app:v1
    imagePullPolicy: IfNotPresent
    env:
    ports:
    - containerPort: 3000
      protocol: TCP
    livenessProbe:
      httpGet:
        path: /healthz
        port: 3000